version: '3'
services:
   redis:
    image: "redis:alpine"
    container_name: my-redis-container

   web:
     build: ./app/
     image: web
     ports: 
       - "5000:5000"
     depends_on:
      - redis
     environment:
      - FLASK_PORT=5000
     container_name: my-web-container

   sleep:
     image: "centos"
     command: sleep 100

   
